#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

PATH="/usr/local/bin:$PATH"

# Format and submit code according to lintstagedrc.js configuration
#pnpm exec lint-staged
pnpm run lint:lint-staged
pnpm run type-check
#pnpm run lint:prettier
#pnpm run lint:eslint
#pnpm run lint:stylelint
